### PR TITLE
Front page

### PR DESCRIPTION
**Pull request by fdezcaminero**
In this project we were able to create a framework of our own similar to Twitter Bootstrap. By doing so we were able to better understand the famous framework.

We chose The Odin Project for its minimalist layouts, which lent themselves to an elegant framework.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# I am in awe! :drooling
This is so awesome! You're readme is fun to read, your framework meets the requirements, you have no validating errors and your clone is almost like the real thing. However, since this is your first review, I want to point out a few things you can adjust to make this job shine at its max potential, and I hope you won't mind as it'll be good for you.

Please consider the following:
#### Resizing
The sizes of the technology stack icons are a bit too large for mobile viewers. Please consider dropping the size appropriately. Please ensure that all elements on the page resize accordingly and don't leave some out of the party :smile: 

#### Padding Inconsistencies
There is a little bit of inconsistency in the padding of your sections, especially in tablet and mobile view. For instance, in tablet mode, your navigation has too much padding on the left and right. You've done such an amazing job and I don't want these little details to ruin your efforts. Please look and make sure your sections and elements are adequately padded.

I wish you best of luck with your next review and I look forward to seeing more beautiful projects like these from you!

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Team!
## Great job on working on all requirements :+1: 
### Just let`s fix few problems and project can be approved

screen
screen

screen
# [OPTIONAL]
Optional which means you can decide not to do them but it would be a good practice. Thanks to this you can learn more:
### Box utilities
#### Margins

*  The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
*  The margins should span from `0 rem` to `1 rem`
*  The margins should have breakpoints (e.g. margin-sm-top-1)

#### Padding

*  The CSS files define separate classes for padding top, bottom, left, right, all padding and auto
*  The padding should span from `0 rem` to `1 rem`
*  The padding should have breakpoints (example padding-lg-2)

### Positioning

#### Floats

*  The CSS files define separate classes for float left, right and clearing the floats

#### Positions

*  The CSS files define separate classes to change the position property of an element to relative, absolute or fixed

### Display

#### Display properties

The CSS files define:

*  A class to set the display property to hidden
* The none class should have breakpoints (example display-md-none)

#### Flex properties

### Colors

#### Background and text

The CSS files define:

* At least ten different classes to set the background and text colors of an element

### Text

#### Utilities

The CSS files define:

*  Classes to horizontally align text to the left, right or center
*  At least five classes to set the font size of an element
*  Three classes to set the font weight of an element (bold, normal, medium)

#### Border

* The CSS files define separate classes for border top, bottom, left, right, all border
* The border should span from 0 to 1rem
* The border should have classes for making box round
* The border should have a class defined to transform a box into a circle

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project still needs changes

**Comment by izaiasneto4** [comment]
### Hi @redacuve and @fdezcaminero. Great work with your project and implementing the changes. Project approved :+1: 

TSE: Izaias Neto

**Pull request merged**
